import Foundation
import AppKit

/// A user-defined routing rule: "if a URL looks like THIS, send it THERE".
struct Rule: Identifiable, Equatable {
    let id: UUID
    var name: String
    var enabled: Bool
    var match: Matcher
    var target: Target

    /// Bundle IDs of apps the link must come *from* for this rule to apply
    /// (e.g. `["com.tinyspeck.slackmacgap", "com.microsoft.teams2"]` →
    /// "links from Slack or Teams"). An **empty array** means the rule
    /// fires regardless of the opener app — that's the default.
    ///
    /// Backward-compatible with the singular `sourceApp` key used by the
    /// first cut of this feature: see `Rule`'s custom `Codable` for the
    /// decode-side lift.
    var sourceApps: [String]

    init(
        id: UUID = UUID(),
        name: String,
        enabled: Bool = true,
        match: Matcher,
        target: Target,
        sourceApps: [String] = []
    ) {
        self.id = id
        self.name = name
        self.enabled = enabled
        self.match = match
        self.target = target
        self.sourceApps = sourceApps
    }
}

// MARK: - Auto-naming
//
// The editor wants a sensible name on a rule the moment the user clicks
// "+", and to keep refining it as they fill in hosts. These helpers
// live on `Rule` so both the sidebar's add action and the editor's
// onChange wiring share one source of truth for the format.

extension Rule {

    /// First-cut name shown on a brand-new rule before the user adds any
    /// hosts. `"Untitled → Safari"` is more useful than `"New rule"` —
    /// it already mentions the destination, which is half the answer.
    static func placeholderName(forTarget bundleID: String) -> String {
        "Untitled → \(browserDisplayName(forBundleID: bundleID))"
    }

    /// The name we'd auto-generate for this rule right now, based on its
    /// first host chip + target browser. `nil` if there's no host to
    /// build a name from yet (we keep the placeholder in that case).
    func autoGeneratedName() -> String? {
        guard let chips = HostChipMatcher.chips(from: match),
              let host = chips.hosts.first(where: { !$0.trimmingCharacters(in: .whitespaces).isEmpty })
        else { return nil }
        return "\(host) → \(Self.browserDisplayName(forBundleID: target.browserBundleID))"
    }

    /// True when the rule's current name is one we generated — meaning
    /// the editor is allowed to keep refining it. The moment the user
    /// types their own name, this returns false and auto-naming steps
    /// out of their way.
    func nameIsAutoGenerated(lastAutoName: String?) -> Bool {
        if name.isEmpty { return true }
        if let last = lastAutoName, name == last { return true }
        // Any "Untitled → <something>" placeholder we created at addRule
        // time also counts as untouched.
        if name.hasPrefix("Untitled → ") { return true }
        return false
    }

    private static func browserDisplayName(forBundleID bundleID: String) -> String {
        if let url = NSWorkspace.shared.urlForApplication(withBundleIdentifier: bundleID) {
            return FileManager.default
                .displayName(atPath: url.path)
                .replacingOccurrences(of: ".app", with: "")
        }
        return bundleID
    }
}

// MARK: - Rule Codable (with sourceApp → sourceApps migration)

extension Rule: Codable {
    private enum CodingKeys: String, CodingKey {
        case id, name, enabled, match, target
        case sourceApps
        case sourceApp   // legacy singular key — read-only, migrated on decode
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.name = try container.decode(String.self, forKey: .name)
        self.enabled = try container.decode(Bool.self, forKey: .enabled)
        self.match = try container.decode(Matcher.self, forKey: .match)
        self.target = try container.decode(Target.self, forKey: .target)

        // Prefer the new key. Fall back to the legacy singular `sourceApp`
        // so rules.json files written by the first cut of source-app rules
        // keep loading. Either key absent = "any source", empty array.
        if let plural = try container.decodeIfPresent([String].self, forKey: .sourceApps) {
            self.sourceApps = plural
        } else if let legacy = try container.decodeIfPresent(String.self, forKey: .sourceApp) {
            self.sourceApps = [legacy]
        } else {
            self.sourceApps = []
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(match, forKey: .match)
        try container.encode(target, forKey: .target)
        // Only write the plural — emitting `sourceApp: null` would create
        // confusing duplication in hand-edited rules.json files.
        try container.encode(sourceApps, forKey: .sourceApps)
    }
}

/// How a rule decides whether a URL matches.
///
/// Three matchers cover the common cases without leaking regex syntax into
/// the JSON for users who just want "github.com → Chrome":
///
/// - `.host("github.com")` matches `github.com` exactly **and** any subdomain
///   (`api.github.com`, `gist.github.com`, ...).
/// - `.hostRegex("...")` runs an arbitrary case-insensitive regex against the
///   URL's host. Power tool — use when `.host` isn't expressive enough.
/// - `.urlContains("/issues/")` matches if the substring appears anywhere in
///   the full URL string. Useful for path-based rules.
/// - `.urlPrefix("https://github.com/NBTSolutions/")` matches if the full
///   URL starts with this prefix (case-insensitive). Anchored — won't
///   false-match `https://evil.com/?ref=github.com/NBTSolutions/`. This
///   is what the editor builds when a user pastes a URL with a path,
///   so "github.com/NBTSolutions/foo" routes only the NBT org's pages.
/// - `.any` matches every URL. Used by source-app-only rules ("everything
///   from Slack → Chrome") where the URL pattern is irrelevant.
enum Matcher: Equatable {
    case host(String)
    case hostRegex(String)
    case urlContains(String)
    case urlPrefix(String)
    case any
}

/// Where a matched URL should be opened.
struct Target: Codable, Equatable {
    var browserBundleID: String
    var profile: String?
    var extraArgs: [String]
    var openInNewWindow: Bool

    init(
        browserBundleID: String,
        profile: String? = nil,
        extraArgs: [String] = [],
        openInNewWindow: Bool = false
    ) {
        self.browserBundleID = browserBundleID
        self.profile = profile
        self.extraArgs = extraArgs
        self.openInNewWindow = openInNewWindow
    }
}

// MARK: - Matcher Codable

extension Matcher: Codable {
    private enum CodingKeys: String, CodingKey {
        case type
        case value
    }

    private enum Kind: String, Codable {
        case host
        case hostRegex
        case urlContains
        case urlPrefix
        case any
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let kind = try container.decode(Kind.self, forKey: .type)
        if kind == .any {
            self = .any
            return
        }
        let value = try container.decode(String.self, forKey: .value)
        switch kind {
        case .host:        self = .host(value)
        case .hostRegex:   self = .hostRegex(value)
        case .urlContains: self = .urlContains(value)
        case .urlPrefix:   self = .urlPrefix(value)
        case .any:         self = .any   // unreachable; handled above
        }
    }

    func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        switch self {
        case .host(let value):
            try container.encode(Kind.host, forKey: .type)
            try container.encode(value, forKey: .value)
        case .hostRegex(let value):
            try container.encode(Kind.hostRegex, forKey: .type)
            try container.encode(value, forKey: .value)
        case .urlContains(let value):
            try container.encode(Kind.urlContains, forKey: .type)
            try container.encode(value, forKey: .value)
        case .urlPrefix(let value):
            try container.encode(Kind.urlPrefix, forKey: .type)
            try container.encode(value, forKey: .value)
        case .any:
            try container.encode(Kind.any, forKey: .type)
        }
    }
}
